// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vssblazfqfizqmudcljk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzc2JsYXpmcWZpenFtdWRjbGprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NjU1MjMsImV4cCI6MjA2NTI0MTUyM30.RudlsstDNDp4bOrunql8XfbM3_WmcR01ut5kjobtN40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);